global:
  scrape_interval: 5s
  evaluation_interval: 5s

scrape_configs:
  - job_name: "gateway"
    static_configs:
      - targets: ["gateway:4000"]

  - job_name: "users-service"
    static_configs:
      - targets: ["users-service:4001"]

  - job_name: "orders-service"
    static_configs:
      - targets: ["orders-service:4002"]
